apiVersion: apps/v1
kind: Deployment
metadata:
  name: dominio-app
spec:
  replicas: 2  # Quantidade de réplicas da aplicação
  selector:
    matchLabels:
      app: dominio-app  # Seleciona pods com essa label
  template:
    metadata:
      labels:
        app: dominio-app  # Associa esse label ao pod criado
    spec:
      containers:
      - name: dominio-app
        image: edsontecno/fiap-dominio:latest  # Imagem do Node.js 
        ports:
        - containerPort: 3000  # Porta exposta pela aplicação
        resources:
          requests:   # Recursos mínimos para cada pod
            memory: "512Mi"
            cpu: "100m"
          limits:     # Limites máximos para cada pod
            memory: "1024Mi"
            cpu: "1"        
        env:
        - name: SERVER_PORT
          value: "3000"  # Porta do servidor
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: host  
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username  
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_NAME
          value: postgres
        - name: DB_ADMIN_EMAIL
          value: admin@root.com
        - name: NODE_ENV
          value: production
